
[dev]
cmd = "bun --watch src/index.ts"
silent = true

[build]
cmd = "bun src/build.ts"

# Benchmarks
[bench-rapide]
cmd = "autocannon -c 100 -d 10 http://localhost:5173"
silent = true

[bench-express]
cmd = "autocannon -c 100 -d 10 http://localhost:5174"
silent = true
